### ISSUE TITLE
[Security] Data safety

### ISSUE THREAD

**Issue by Ocimum-basilicum** [Ecoxl/celero#14]
As discussed in our first code review last week we need to guarantee that we don't have data leaks if we possess real costumer data. We found debug code which allows everyone to get a companies data in JSON format. Not even a valid user session/login is required.

It is very important that we get rid of these code! If such critical code is used for functionality we need to implement proper user permission so that this is not public available.

**Comment by tcgumus** [comment]
I cant say im fan of this tone 🙁

User permission is already implemented but it is disabled by xammp to access and debug some of the fields so we can work faster.

I will put these implementation on to-do list. Everything have an order. 

I’m and will keep Dirk informed. Close these issues by his request. 

Thanks :)

**Comment by Ocimum-basilicum** [comment]
I didn't wan't to offend you in any way. I just wanted to write down our impressions from the code review. You know the code better than any of us and we need your help to tackle such problems. Maybe its not as crucial as it looks and you already know the background and how to fix it :)
