### ISSUE TITLE
[Security] User permissions

### ISSUE THREAD

**Issue by Ocimum-basilicum** [Ecoxl/celero#15]
As discussed in our first code review last week we need to have proper user permissions inside our application. Everyone can register/sign up for celero but not everyone should be allowed to see all data. The user permission is implemented individual for almost every function in the user controller. This is not really manageable and we are unsure which functionality is accessible for whom.

We need to think about moving the user permission control to one place. Codeigniters [Auth library](http://codeigniter-aauth-test.readthedocs.io/en/latest/index.html) would offer such features out of the box.

**Comment by tcgumus** [comment]
Hello 
Users have permissions. Not all users can access all projects. As i know we can define more but the user permission admin tool was made by another developer. What happened to it? 🙂
