### ISSUE TITLE
Forgot password feature not working, review needed

### ISSUE THREAD

**Issue by Ocimum-basilicum** [Ecoxl/celero#21]
The "forgot password" feature is currently not working. The site /new_password_email allows to enter an email address to receive a new password. The sendMail function (line 164under [/application/controller/Password.php](https://github.com/Ecoxl/celero/blob/master/application/controllers/Password.php) is no configured to work properly. It needs an email account which will send out those mails. Expecting more errors when the feature is functional. 

In my opinion this feature needs to be reviewed. For an upcoming release it needs to be reliable and meet todays security standards!

**Comment by tcgumus** [comment]
we can use maligun.com. it is free to 10000 email per month and we can be sure it won't be in the spam folder

**Comment by tcgumus** [comment]
are there any update to that?

**Comment by Ocimum-basilicum** [comment]
This was implemented by @tcgumus and is working fine! Therefore I close this!
