### ISSUE TITLE
CELERO documentation

### ISSUE THREAD

**Issue by Ocimum-basilicum** [Ecoxl/celero#22]
We should start to write a documentation about the technical parts of CELERO. We improved the software overall by moving to Docker, upgrading CI, fixing bugs and so on. If we don't document anything further development, especially for people who join/take over the project in the future, will be very hard. 

My suggestion is to start here on github by expanding the README.md. First we should start with "meta informations" about frameworks used and how the code is designed and how docker is used. Some documentations already exist but if they are stored private they don't help anyone.

**Comment by tcgumus** [comment]
Yes. Definitly. We can use wiki in here and also i will start adding phpdoc to classes as well.
