### ISSUE TITLE
Tool tip company page: Explain what a user is

### ISSUE THREAD

**Issue by Ecoxl** [Ecoxl/celero#44]

**Comment by Xandalfius** [comment]
I think a little "(?)" tooltip for the "Become Consultant" Box would be enough:

"Consultants have full access to all functionalities of the Platform."


What is probably not implemented yet, but was already written in the Manual (and I didn't take it out):

"If you apply for consultant, the administrator has to approve it." (This may take xy days/hours)



![image](https://user-images.githubusercontent.com/69843619/93067247-43600d00-f67b-11ea-84fb-6915d8de14fe.png)

**Comment by tcgumus** [comment]
Both Tooltips are added.

![image](https://user-images.githubusercontent.com/2714346/97089374-e96e4200-163f-11eb-8437-1a348f64f92c.png)
