### ISSUE TITLE
Tool tip: Explain Environmental impact indicator (EP) 

### ISSUE THREAD

**Issue by Ecoxl** [Ecoxl/celero#47]

**Comment by Xandalfius** [comment]
The Environmental Impact calculator is derived from "XYXY". (I don't know, but it's a plugin from another website?)

It helps calculate the environmental impact based on the UBP-Values of "Licence" or the data you added under "My EP Data".

**Comment by tcgumus** [comment]
![image](https://user-images.githubusercontent.com/2714346/97091710-82a05700-1646-11eb-821f-2e266dd32260.png)
updated.
