### ISSUE TITLE
PHP Error after adding new flow with m^3 as unit.

### ISSUE THREAD

**Issue by Xandalfius** [Ecoxl/celero#71]
After creating a new Flow for Waste Water (Endoflife-treatment) with m3 as unit using the Environmental impact calculator, the following Error occurred.

https://32038.hostserv.eu/new_flow/3451

I reproduced it several times, but it happened only for this specific lvl 2 Flow Name, probably due to the unit: m^3

My Input:
<img width="946" alt="Error_Flow_M3_input" src="https://user-images.githubusercontent.com/69843619/90647499-a99e6f00-e238-11ea-9c3e-9d41b45cbee2.PNG">

The Error message:
<img width="939" alt="Error_Flow_M3" src="https://user-images.githubusercontent.com/69843619/90647396-9095be00-e238-11ea-9695-10b00c3f1d4a.PNG">

**Comment by Xandalfius** [comment]
The same Type of Error shows up for the unit m^2 for the flow "Cladding".

<img width="913" alt="Error_Flow_M2_input" src="https://user-images.githubusercontent.com/69843619/90763664-5fc09200-e2e7-11ea-8e53-f4172d879dec.PNG">

**Comment by tcgumus** [comment]
hello,
flow_model has a method called get_unit_list. Later in controller, it checks if the quantity_unit_id is equal to name of quantity from this method. I'm not sure but i think m3 and m2 quantities are not in the list of active unit list. @Ocimum-basilicum, can you check that? 

Code which selects units are as follow:

		$this->db->select("*");
		$this->db->from("t_unit");
		$this->db->where('active',1);
		$this->db->order_by("id", "asc");

**Comment by Ocimum-basilicum** [comment]
Exactly the units "m3" and "m2" are not in the DB unit list. I just changed the JS code to replace the units to the correct superscript numbers. Fixed with commit https://github.com/Ecoxl/celero/commit/90ce5a1279919f76b328ff49b7880f57be494348
