### ISSUE TITLE
Improvement: When creating a project and data is missing, the other data gets lost.

### ISSUE THREAD

**Issue by Xandalfius** [Ecoxl/celero#73]
As someone pointed out in the User Manual (gonna remove it from there):

When creating a project and selecting a location on the map, if the saving fails due to missing data in another field, the location get lost and this was a little annoying always reselect the point on the map (until I found the field with the missing data).
Also the chosen Companies and Consultants get thrown out if there was missing information in a mandatory field.

It would be a nice QoL-Improvement to have the data cached that was already put in.
Also mark the mandatory fields with a red * as in other pages.

**Comment by tcgumus** [comment]
it is now remembering selected value and also show red required test over required fields
