### ISSUE TITLE
Improvement: Adding Users to Company

### ISSUE THREAD

**Issue by Xandalfius** [Ecoxl/celero#75]
By choosing a Company under _My Companies_ you can give other Users the permission to edit said company by clicking _Add New User_.

This button could also be in the company creation window as it is with creating projects.

![image](https://user-images.githubusercontent.com/69843619/90889189-f3fa2a00-e3b7-11ea-9341-c12f9ff76819.png)

**Comment by Xandalfius** [comment]
For comparison: The Add Project-Page:
![image](https://user-images.githubusercontent.com/69843619/91052150-599d1f00-e621-11ea-9c8f-02fa135fd533.png)

**Comment by Xandalfius** [comment]
I think a Tooltip/Infobox would be nice:

(?)
Here you can give other Users access to your Project/Company.

**Comment by tcgumus** [comment]
Hello, i have finished it and pushed it.
