### ISSUE TITLE
Improvement: Environment Impact Calculator

### ISSUE THREAD

**Issue by Xandalfius** [Ecoxl/celero#77]
Would be nice to have some kind of tooltip which tells you that, if you want to add a flow which is not in the List, you have to go back and define it (and its' UBP) under _My EP Data_.

Also, considering the List of potential flows might grow, a text search function (maybe integrated in the greyed out "flow name" field) would come in handy.

**Comment by tcgumus** [comment]
Warning added:
![image](https://user-images.githubusercontent.com/2714346/97091280-7c5cab80-1643-11eb-83b8-643325a21ef0.png)

I will add a new issue for text search.
